update implementation
mF2C/dataClay pull request #33
Opened 2019-01-30 14:49 UTC by loomis

Update the implementation of the proxy by refining the error handling and refactoring to allow a direct connection from the CIMI server to dataClay eventually (not currently working).

2019-01-30 16:06 UTC, cjdcordeiro requested changes
@loomis I can't build it:

```
Step 12/16 : ADD ./target/proxy-0.1.0-SNAPSHOT-standalone.jar /root/dataclay/proxy.jar
ADD failed: stat /var/lib/docker/tmp/docker-builder960612566/target/proxy-0.1.0-SNAPSHOT-standalone.jar: no such file or directory
```

2019-01-31 07:36 UTC, loomis commented
@cjdcordeiro I've fixed the bad reference to the jar file.  It should build correctly now.  I've also removed the old wrapper and support scripts.

2019-01-31 09:33 UTC, cjdcordeiro approved these changes
tested and working

2019-01-31 09:33 UTC, cjdcordeiro commented on dataclay-proxy/project.clj
> -(defproject com.sixsq.dataclay/proxy "0.1.0-SNAPSHOT"
I think this is the faulty line

2019-01-31 09:33 UTC, merged